version: '3.3'

services:
  apimoney:
    image: toto_api_money:0.0.3
    build: "."
    ports:
      - "6062"
    restart: "always"
    networks:
      - "totoapimoney.network"
    deploy:
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 5s
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apimoney
    ports:
      - "6061:6061"
    restart: always
    networks:
      - "totoapimoney.network"
networks:
  totoapimoney.network: